### PR TITLE
Added NetStub with nextResult property.

### PR DESCRIPTION
**Pull request by alexruperez**
### Goals ⚽
Testing.

### Implementation Details 🚧
NetStub class conforming Net protocol and NetTaskStub NetTask subclass.
Some open functions have changed to public.

### Testing Details 🔍
Just set nextResponse property of NetStub instance to desired test result.

---
This change is [Reviewable](https://reviewable.io/reviews/intelygenz/netclient-ios/11)

### CODE REVIEW

**Comment by RobertoEstrada** [comment]
Review status: 0 of 20 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[Alamofire/NetAlamofire.swift, line 11 at r1](https://reviewable.io:443/reviews/intelygenz/netclient-ios/11#-L3gSR_LSTNWf--LYYWO:-L3gSR_MuX6auXOZyidc:bae1ybg) ([raw file](https://github.com/intelygenz/netclient-ios/blob/4339bf8d45e8187ee60c01b7b7bffd01aab7229d/Alamofire/NetAlamofire.swift#L11)):*
> ```Swift
> import Alamofire
> 
> open class NetAlamofire: Net {
> ```

This class is the final client, therefore this should be left as `public` and `final` because you don't want anyone overriding this implementation but, you want anyone writing its own one.

This should help you enforce the open/close principle in your class, leaving it open for `extension`but *closed* for modification

---

*[Core/NetTask.swift, line 99 at r1](https://reviewable.io:443/reviews/intelygenz/netclient-ios/11#-L3gUIx5RJCb7MY27_B7:-L3gUIx5RJCb7MY27_B8:b4o91tj) ([raw file](https://github.com/intelygenz/netclient-ios/blob/2c7697d793538b268d1c00521c15b7e044859338/Core/NetTask.swift#L99)):*
> ```Swift
> }
> 
> extension NetTask {
> ```

Don't remove your extensions just because there is an `open` method inside. Before, ask yourself if that `open` is meant to be overriden. 

If the answer is clearly **NO**, just set it `public` and leave it live inside its own extension. 

---

*[Core/NetTask.swift, line 215 at r1](https://reviewable.io:443/reviews/intelygenz/netclient-ios/11#-L3gUwQtL3-fRqeXaTeF:-L3gUwQtL3-fRqeXaTeG:bkampvo) ([raw file](https://github.com/intelygenz/netclient-ios/blob/4339bf8d45e8187ee60c01b7b7bffd01aab7229d/Core/NetTask.swift#L215)):*
> ```Swift
> }
> 
> extension NetTask: NetTaskProtocol {}
> ```

If a class conforms to multiple protocols but, none of the implementations are on the extensions just make the original type conform to all of them and let the user see for himself in the first lines of the file which protocols this type conforms to instead hiding it in the last bottom lines of the file

---

*[URLSession/NetURLSession.swift, line 11 at r1](https://reviewable.io:443/reviews/intelygenz/netclient-ios/11#-L3gWZmrpYJzn00n29vX:-L3gWZmrpYJzn00n29vY:b-wa2hfy) ([raw file](https://github.com/intelygenz/netclient-ios/blob/4339bf8d45e8187ee60c01b7b7bffd01aab7229d/URLSession/NetURLSession.swift#L11)):*
> ```Swift
> import Foundation
> 
> open class NetURLSession: Net {
> ```

This class is the final client, therefore this should be left as `public` and `final` because you don't want anyone overriding this implementation but, you want anyone writing its own one.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/intelygenz/netclient-ios/11)*

**Comment by alexruperez** [comment]
Review status: 0 of 20 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[Alamofire/NetAlamofire.swift, line 11 at r1](https://reviewable.io:443/reviews/intelygenz/netclient-ios/11#-L3gSR_LSTNWf--LYYWO:-L3gb-OMgDmTMKkZ28z5:b-ncjxmj) ([raw file](https://github.com/intelygenz/netclient-ios/blob/4339bf8d45e8187ee60c01b7b7bffd01aab7229d/Alamofire/NetAlamofire.swift#L11)):*
<details><summary><i>Previously, RobertoEstrada (Roberto Estrada) wrote…</i></summary><blockquote>

This class is the final client, therefore this should be left as `public` and `final` because you don't want anyone overriding this implementation but, you want anyone writing its own one.

This should help you enforce the open/close principle in your class, leaving it open for `extension`but *closed* for modification
</blockquote></details>

I've open it in case someone wants to modify a part of that implementation we've done because he thinks it has a wrong behavior or he needs for a particular project, but he does not want to duplicate all the code in a new implementation for just change one thing. Sometimes it has happened to me that I want to modify something from a library but because of a need of my project and doing a pull request not make sense.

And Alamofire also opened the SessionManager: https://github.com/Alamofire/Alamofire/blob/master/Source/SessionManager.swift#L28

And one question, what is the `final` advantage for outside a module/framework if it's public and not open?

Thanks!

---

*[Core/NetTask.swift, line 99 at r1](https://reviewable.io:443/reviews/intelygenz/netclient-ios/11#-L3gUIx5RJCb7MY27_B7:-L3gdOk8-IqAdCTTfRPZ:breewtx) ([raw file](https://github.com/intelygenz/netclient-ios/blob/2c7697d793538b268d1c00521c15b7e044859338/Core/NetTask.swift#L99)):*
<details><summary><i>Previously, RobertoEstrada (Roberto Estrada) wrote…</i></summary><blockquote>

Don't remove your extensions just because there is an `open` method inside. Before, ask yourself if that `open` is meant to be overriden. 

If the answer is clearly **NO**, just set it `public` and leave it live inside its own extension. 
</blockquote></details>

I think someone might want to subclass a NetTask to change the behaviour.

Just like Alamofire: https://github.com/Alamofire/Alamofire/blob/c4b4bb4206af735c1b34c8512324c8c22583a563/Source/Request.swift#L355

---

*[Core/NetTask.swift, line 215 at r1](https://reviewable.io:443/reviews/intelygenz/netclient-ios/11#-L3gUwQtL3-fRqeXaTeF:-L3geTl0owgsKXOORIx7:b3jftm8) ([raw file](https://github.com/intelygenz/netclient-ios/blob/4339bf8d45e8187ee60c01b7b7bffd01aab7229d/Core/NetTask.swift#L215)):*
<details><summary><i>Previously, RobertoEstrada (Roberto Estrada) wrote…</i></summary><blockquote>

If a class conforms to multiple protocols but, none of the implementations are on the extensions just make the original type conform to all of them and let the user see for himself in the first lines of the file which protocols this type conforms to instead hiding it in the last bottom lines of the file
</blockquote></details>


I just follow our style guide, maybe you want to make a pull request specifying this concrete case. https://gitlab.intelygenz.com/daniel.coello/igz-swift-styleguide/blob/master/README.md#protocol-conformance

---

*[URLSession/NetURLSession.swift, line 11 at r1](https://reviewable.io:443/reviews/intelygenz/netclient-ios/11#-L3gWZmrpYJzn00n29vX:-L3gelPBrD0nWfaxfook:b-ncjxmj) ([raw file](https://github.com/intelygenz/netclient-ios/blob/4339bf8d45e8187ee60c01b7b7bffd01aab7229d/URLSession/NetURLSession.swift#L11)):*
<details><summary><i>Previously, RobertoEstrada (Roberto Estrada) wrote…</i></summary><blockquote>

This class is the final client, therefore this should be left as `public` and `final` because you don't want anyone overriding this implementation but, you want anyone writing its own one.
</blockquote></details>

I've open it in case someone wants to modify a part of that implementation we've done because he thinks it has a wrong behavior or he needs for a particular project, but he does not want to duplicate all the code in a new implementation for just change one thing. Sometimes it has happened to me that I want to modify something from a library but because of a need of my project and doing a pull request not make sense.

And Alamofire also opened the SessionManager: https://github.com/Alamofire/Alamofire/blob/master/Source/SessionManager.swift#L28

And one question, what is the `final` advantage for outside a module/framework if it's public and not open?

Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/intelygenz/netclient-ios/11)*

**Comment by RobertoEstrada** [comment]
Review status: 0 of 22 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[Alamofire/NetAlamofire.swift, line 11 at r1](https://reviewable.io:443/reviews/intelygenz/netclient-ios/11#-L3gSR_LSTNWf--LYYWO:-L3gi37o7O4soouBqCmU:blile46) ([raw file](https://github.com/intelygenz/netclient-ios/blob/4339bf8d45e8187ee60c01b7b7bffd01aab7229d/Alamofire/NetAlamofire.swift#L11)):*
<details><summary><i>Previously, alexruperez (Alex Rupérez) wrote…</i></summary><blockquote>

I've open it in case someone wants to modify a part of that implementation we've done because he thinks it has a wrong behavior or he needs for a particular project, but he does not want to duplicate all the code in a new implementation for just change one thing. Sometimes it has happened to me that I want to modify something from a library but because of a need of my project and doing a pull request not make sense.

And Alamofire also opened the SessionManager: https://github.com/Alamofire/Alamofire/blob/master/Source/SessionManager.swift#L28

And one question, what is the `final` advantage for outside a module/framework if it's public and not open?

Thanks!
</blockquote></details>

LGTM. If you want it `open` because you want it and most importantly *designed it that way* to provide extension points that's fine to me.

As for the `final` modifier question, `final` closes the class for subclassing at all levels. While `open` states to the world outside of your module that your class is overridable,  `public`,`internal`, `private` and `fileprivate`classes *CAN* still be subclassed from *inside* your module unless they are marked as `final`.

Marking your classes as `final`, besides complying with the style guide in the subject of 'favoring final classes' brings in some compiler optimizations like getting rid of dynamic method dispatching. You can read more about it in this article: [\'The Importance of being `final`\' ](http://blog.human-friendly.com/the-importance-of-being-final)

---

*[Core/NetTask.swift, line 99 at r1](https://reviewable.io:443/reviews/intelygenz/netclient-ios/11#-L3gUIx5RJCb7MY27_B7:-L3gmYDZGQ6eGP6wQRqE:bb425hv) ([raw file](https://github.com/intelygenz/netclient-ios/blob/2c7697d793538b268d1c00521c15b7e044859338/Core/NetTask.swift#L99)):*
<details><summary><i>Previously, alexruperez (Alex Rupérez) wrote…</i></summary><blockquote>

I think someone might want to subclass a NetTask to change the behaviour.

Just like Alamofire: https://github.com/Alamofire/Alamofire/blob/c4b4bb4206af735c1b34c8512324c8c22583a563/Source/Request.swift#L355
</blockquote></details>

OK, fine then!

---

*[Core/NetTask.swift, line 215 at r1](https://reviewable.io:443/reviews/intelygenz/netclient-ios/11#-L3gUwQtL3-fRqeXaTeF:-L3gnYJ5kxXpPtPap8x7:bl9xwm9) ([raw file](https://github.com/intelygenz/netclient-ios/blob/4339bf8d45e8187ee60c01b7b7bffd01aab7229d/Core/NetTask.swift#L215)):*
<details><summary><i>Previously, alexruperez (Alex Rupérez) wrote…</i></summary><blockquote>

I just follow our style guide, maybe you want to make a pull request specifying this concrete case. https://gitlab.intelygenz.com/daniel.coello/igz-swift-styleguide/blob/master/README.md#protocol-conformance
</blockquote></details>

Actually, reading the style guide, it does not rule nor rule out this edge case so we're in quite an alegal situation. For the moment I'm going to consider this OK but i'm going to propose an exception for cases like this in the style guide.

---

*[URLSession/NetURLSession.swift, line 11 at r1](https://reviewable.io:443/reviews/intelygenz/netclient-ios/11#-L3gWZmrpYJzn00n29vX:-L3gqI3wgiIjnuFlCa7a:b6xsw) ([raw file](https://github.com/intelygenz/netclient-ios/blob/4339bf8d45e8187ee60c01b7b7bffd01aab7229d/URLSession/NetURLSession.swift#L11)):*
<details><summary><i>Previously, alexruperez (Alex Rupérez) wrote…</i></summary><blockquote>

I've open it in case someone wants to modify a part of that implementation we've done because he thinks it has a wrong behavior or he needs for a particular project, but he does not want to duplicate all the code in a new implementation for just change one thing. Sometimes it has happened to me that I want to modify something from a library but because of a need of my project and doing a pull request not make sense.

And Alamofire also opened the SessionManager: https://github.com/Alamofire/Alamofire/blob/master/Source/SessionManager.swift#L28

And one question, what is the `final` advantage for outside a module/framework if it's public and not open?

Thanks!
</blockquote></details>

LGTM. Same reason as previously stated.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/intelygenz/netclient-ios/11)*

**Comment by RobertoEstrada** [comment]
:lgtm:

---

Review status: 0 of 22 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/intelygenz/netclient-ios/11#-:-L3gqp3xHs_Ky2v95iCj:bnfp4nl)*

**Comment by alexruperez** [comment]
Thanks for the review and the explanations @RobertoEstrada! 😃

**Review by RobertoEstrada — APPROVED** [review]

**Comment by RobertoEstrada** [comment]
Reviewed 17 of 20 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/intelygenz/netclient-ios/11)*

**Comment by juantrias** [comment]
Reviewed 17 of 20 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[Core/NetTask.swift, line 215 at r1](https://reviewable.io:443/reviews/intelygenz/netclient-ios/11#-L3gUwQtL3-fRqeXaTeF:-L46xiLEPnaxdQ7AkDkh:by6t65n) ([raw file](https://github.com/intelygenz/netclient-ios/blob/4339bf8d45e8187ee60c01b7b7bffd01aab7229d/Core/NetTask.swift#L215)):*
<details><summary><i>Previously, RobertoEstrada (Roberto Estrada) wrote…</i></summary><blockquote>

Actually, reading the style guide, it does not rule nor rule out this edge case so we're in quite an alegal situation. For the moment I'm going to consider this OK but i'm going to propose an exception for cases like this in the style guide.
</blockquote></details>

I agree with @RobertoEstrada. In this case I see no real benefit on declaring protocol conformance in extensions, since this extensions need to be empty because of the problem with open members declared inside extensions https://gitlab.intelygenz.com/daniel.coello/igz-swift-styleguide/issues/4. Maybe we can put `// MARK:` comments to separate the implementation of the different protocols

---

*[Stub/NetStub.swift, line 18 at r1](https://reviewable.io:443/reviews/intelygenz/netclient-ios/11#-L3gG059Y-JFQdxiJk2Q:-L3gG05AHnTGHrGHIwSj:bdibs1e) ([raw file](https://github.com/intelygenz/netclient-ios/blob/4339bf8d45e8187ee60c01b7b7bffd01aab7229d/Stub/NetStub.swift#L18)):*
> ```Swift
>     open static var shared: Net = NetStub()
> 
>     open var requestInterceptors = [RequestInterceptor]()
> ```

Could be `requestInterceptors` and `responseInterceptors` private? I understand that `nextResult` needs to be public because it's the way to mock a response

---

*[Stub/NetStub.swift, line 42 at r1](https://reviewable.io:443/reviews/intelygenz/netclient-ios/11#-L3gHoaNIF3pf0i9NrFl:-L3gHoaNIF3pf0i9NrFm:b-fqp5rn) ([raw file](https://github.com/intelygenz/netclient-ios/blob/4339bf8d45e8187ee60c01b7b7bffd01aab7229d/Stub/NetStub.swift#L42)):*
> ```Swift
>         if let builder = requestBuilder {
>             requestInterceptors.forEach({ interceptor in
>                 requestBuilder = interceptor(builder)
> ```

It seems like you are passing the same `builder` object to each interceptor in the chain, so you are overwriting the `requestBuilder` in each iteration ignoring the result of the previous interceptor

---

*[Stub/NetStub.swift, line 46 at r1](https://reviewable.io:443/reviews/intelygenz/netclient-ios/11#-L3gJ1tlLZNj-iZogfIe:-L3gJ1tlLZNj-iZogfIf:bpwf9v7) ([raw file](https://github.com/intelygenz/netclient-ios/blob/4339bf8d45e8187ee60c01b7b7bffd01aab7229d/Stub/NetStub.swift#L46)):*
> ```Swift
>         }
>         guard let nextResult = nextResult else {
>             return NetTaskStub(request: requestBuilder?.build())
> ```

NetTaskStub.request should be optional? Can we have a NetTask without a request? The `request` parameter of `stub()` should be optional?

---

*[Stub/NetTaskStub.swift, line 10 at r2](https://reviewable.io:443/reviews/intelygenz/netclient-ios/11#-L470mGW0pfijizuHzYU:-L470mGW0pfijizuHzYV:b9u4lgb) ([raw file](https://github.com/intelygenz/netclient-ios/blob/fa0f7d34e73bbc54f0a0da00b414dea176172c02/Stub/NetTaskStub.swift#L10)):*
> ```Swift
> import Foundation
> 
> class NetTaskStub: NetTask {
> ```

Could be NetTaskStub a protocol implementation instead of a NetTask subclass? I generally prefer implement protocols over inheritance for mocks, to clearly separate the mock from the production code and do not end calling by accident production code in the tests. Maybe in this case we need to reuse much of the NetTask code for the Stub and it is OK to inherit, or to place the common code in a NetTask protocol extension

---

*[Stub/NetTaskStub.swift, line 15 at r2](https://reviewable.io:443/reviews/intelygenz/netclient-ios/11#-L4716Ud699f0XZUMZ1Y:-L4716Ud699f0XZUMZ1Z:b-iq313h) ([raw file](https://github.com/intelygenz/netclient-ios/blob/fa0f7d34e73bbc54f0a0da00b414dea176172c02/Stub/NetTaskStub.swift#L15)):*
> ```Swift
>         completionClosure = completion
>         progressClosure?(Progress(totalUnitCount: 0))
>         completion?(response, error)
> ```

If we do not stub `response` or `error` we will call completion block with both params nil. Should we return a "Next result not specified." error like in `sync()`?

---

*[URLSession/NetURLSession.swift, line 11 at r2](https://reviewable.io:443/reviews/intelygenz/netclient-ios/11#-L4AMbQgcQV27BkCAYEW:-L4AMbQgcQV27BkCAYEX:blu0kzh) ([raw file](https://github.com/intelygenz/netclient-ios/blob/fa0f7d34e73bbc54f0a0da00b414dea176172c02/URLSession/NetURLSession.swift#L11)):*
> ```Swift
> import Foundation
> 
> open class NetURLSession: Net {
> ```

Should be open instead of public? Why a client would need to override instead of extend NetURLSession? Same for NetAlamofire and the rest of adapters

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/intelygenz/netclient-ios/11)*

**Pull request merged**
